### ISSUE TITLE
Consume the dep binary from the Paketo dep-server

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/dep#212]
Per https://github.com/paketo-buildpacks/dep-server/issues/45, we should start consuming the `dep` dependency from the dep-server (See https://api.deps.paketo.io/v1/dependency?name=dep for dependency metadata) instead of the https://buildpacks.cloudfoundry.org/dependencies/dep/... location we currently get the dependencies from.

This will make the dependency publishing/consumption process more transparent than the process we use for the dependencies available via the [dependency-builds pipeline](https://buildpacks.ci.cf-app.com/teams/main/pipelines/dependency-builds).

We have already done this switch-over in the Node Engine and Yarn Buildpacks. The outline of what this work will entail can be found in the dep-server issue linked at the top.

**Comment by fg-j** [comment]
This is blocked until the dep server supports the `dep` dependency. Currently, hitting the dependency API endpoint (https://api.deps.paketo.io/v1/dependency?name=dep) returns an error.

**Comment by sophiewigmore** [comment]
@fg-j I don't actually think that the `dep` dependency is in the dependency builds pipeline either (probably because it's deprecated by Golang in favour of go modules). It looks like the version of the dependency in the `buildpack.toml` has not been updated in 12 months, and was last updated by hand. We probably don't need this issue, since we have no reason to poll for new `dep` versions in the dep-server

**Comment by ryanmoran** [comment]
The [`golang/dep` repo](https://github.com/golang/dep) has been archived and there will be no future releases. Support for `dep` only exists as a legacy support mechanism and will be removed once `go.mod` becomes the only package management mechanism.

**Comment by fg-j** [comment]
In that case, it sounds like we don't actually care to consume dep from the dep-server. Closing for now. Feel free to re-open if I've got the wrong idea here.
